### ISSUE TITLE
Doesn't compile on Ubuntu 24.04

### ISSUE THREAD

**Issue by j1warren** [trezor/blockbook#1131]
see here 
https://github.com/trezor/blockbook/issues/45#issuecomment-2351618401

**Comment by j1warren** [comment]
https://github.com/facebook/rocksdb/commit/88edfbfb5e1cac228f7cc31fbec24bb637fe54b1
https://github.com/facebook/rocksdb/pull/12171/files

Fixed it with this in `build/docker/bin/Dockerfile`

```
# install rocksdb
RUN cd /opt && git clone -b $ROCKSDB_VERSION --depth 1 https://github.com/facebook/rocksdb.git
+RUN cd /opt/rocksdb && sed -i '8i #include <cstdint>' table/block_based/data_block_hash_index.h && sed -i '9i #include <cstdint>' util/string_util.h && sed -i '11i #include <cstdint>' include/rocksdb/utilities/checkpoint.h
+RUN cd /opt/rocksdb && CFLAGS=-fPIC CXXFLAGS="-fPIC -Wno-error=redundant-move" PORTABLE=$PORTABLE_ROCKSDB make -j 4 release
-RUN cd /opt/rocksdb && CFLAGS=-fPIC CXXFLAGS=-fPIC PORTABLE=$PORTABLE_ROCKSDB make -j 4 release
RUN strip /opt/rocksdb/ldb /opt/rocksdb/sst_dump && \
    cp /opt/rocksdb/ldb /opt/rocksdb/sst_dump /build
```

**Comment by ogunden** [comment]
Just confirmed this issue is still outstanding at blockbook commit bcc68b89399d86c43b4e430455579450815a102a.

Also confirmed that adding the `sed` line above to `build/docker/bin/Dockerfile` fixes it. I didn't have to add the `-Wno-error=redundant-move` however. It looks like that's been taken care of by the addition of `DISABLE_WARNING_AS_ERROR=1`.
