### ISSUE TITLE
Addresses begin with bc1 while running with bitcoin testnet4

### ISSUE THREAD

**Issue by ertenmehmet** [trezor/blockbook#1154]
Running couple of different instances of blockbook while managing our migration to testnet4,
We have noticed that in the explorer interface it shows addresses as begin with bc1 style e.g bc1qgrcex95y6mdankp5t5uz6wlwve6333pjdt4v4m; instead of tb1qhjxlhw07m9tcm07tjzufjxt47m26qqq2gmsdtg

But when it comes to resolving them it is ok, when requested testnet4-blockbook-url/api/v2/address/tb1qhjxlhw07m9tcm07tjzufjxt47m26qqq2gmsdtg it responds successfully, but with
`"address": "bc1qhjxlhw07m9tcm07tjzufjxt47m26qqq2zat7sm"`

also noticed in the logs:
`1 bitcoinrpc.go:146] rpc: block chain mainnet`

Environment is as follows:
newly built from https://github.com/trezor/blockbook/commit/fe676b35
and running with the following config
```
{
    "network": "test",
    "coin_name": "Testnet4",
    "coin_shortcut": "TEST",
    "coin_label": "Bitcoin Testnet4",
    "coin_alias": "bitcoin_testnet4",
    "rpc_url": "http://bitcoind:18030",
    "rpc_user": "rpc",
    "rpc_pass": "rpc",
    "rpc_timeout": 25,
    "parse": true,
    "message_queue_binding": "tcp://bitcoind:48332",
    "subversion": "",
    "address_format": "",
    "xpub_magic": 70617039,
    "xpub_magic_segwit_p2sh": 71979618,
    "xpub_magic_segwit_native": 73342198,
    "slip44": 1,
    "mempool_workers": 1,
    "mempool_sub_workers": 1,
    "block_addresses_to_keep": 300
}
```
and running with the following parameters
`blockbook -blockchaincfg=/opt/etc/blockchaincfg.json -datadir=/opt/data -workers=1 -sync -internal=:19030 -public=:19130 -explorer= -logtostderr`

We also have our own bitcoin node, running with the 28.0.0 official release from https://bitcoincore.org

Not sure if we miss something with the configuration or something we miss while building blockbook; or an actual issue.

**Comment by wakiyamap** [comment]
https://github.com/trezor/blockbook/issues/1130#issuecomment-2413348490
Maybe this will fix it.

**Comment by ertenmehmet** [comment]
so @wakiyamap, would it be running as expected (by showing actual wallet addresses with tb1) if we build and run from your fork?

**Comment by wakiyamap** [comment]
@ertenmehmet 
My fork now shows `tb1`. I've reported it to the current pull request. Thanks for letting me know!
https://testnet4-explorer.wakiyamap.dev/

**Comment by ertenmehmet** [comment]
Hey @wakiyamap I thank you instead, just compiled and deployed a version from your testnet4 specific branch and it works like charm!!
Thank you so much! and hope they'll merge it soon :))

**Comment by martinboehm** [comment]
Fixed by f373a73beaf31bd7bb33343946ac94bf2ddad8b8

**Comment by antondalgren** [comment]
Im still seeing this issue even tho we are running the code from this commit: https://github.com/trezor/blockbook/commit/4a7fdb509569a31ada721801d1ff57ad88afa553

Is anyone else seeing this issue? Could we have done a misconfiguration somehow?

**Comment by martinboehm** [comment]
Our servers show `tb1` addresses, see for example https://tbtc4-1.trezor.io/tx/eb01e404bee47c4fd51ea41ab07cd7c96e47f06a57bdea93056b236da9285686
