### ISSUE TITLE
BSV mainnet, stuck at 1662583499 

### ISSUE THREAD

**Issue by timurgum** [trezor/blockbook#802]
Hello,
today blockbook stuck at BSV mainnet with error:

bsv.blockbook    | I0908 04:02:26.075428       1 blockbook.go:138] Blockbook: {Version:devel GitCommit:df324d1 BuildTime:2022-04-20T09:02:36+00:00 GoVersion:go1.17.1 OSArch:linux/amd64}, debug mode true
bsv.blockbook    | I0908 04:02:26.079347       1 bcashrpc.go:61] rpc: block chain mainnet
bsv.blockbook    | I0908 04:02:26.079392       1 mempool_bitcoin_type.go:56] mempool: starting with 8*2 sync workers
bsv.blockbook    | I0908 04:02:26.079406       1 rocksdb.go:148] rocksdb: opening /opt/bitcoin-sv/blockbook/db, required data version 5, cache size 16384, max open files 16384
bsv.blockbook    | fatal error: unexpected signal during runtime execution
bsv.blockbook    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f873d715105 pc=0x7f8af4f5337d]

**Comment by APshenkin** [comment]
faced same issue as well
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f481c021000 pc=0x7f48bcc168eb]
runtime stack:
runtime.throw({0x11492b4, 0x7f48bc226c1e})
	/tmp/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/tmp/go/src/runtime/signal_unix.go:719 +0x396
goroutine 1 [syscall]:
runtime.cgocall(0xc3c188, 0xc00014b5b8)
	/tmp/go/src/runtime/cgocall.go:156 +0x5c fp=0xc00014b590 sp=0xc00014b558 pc=0x52d1dc
github.com/flier/gorocksdb._Cfunc_rocksdb_open_column_families(0x7f488c007030, 0x7f488c00a4f0, 0x8, 0xc0000d7040, 0xc0000d1240, 0xc0000d1280, 0xc0001280e0)
	_cgo_gotypes.go:2261 +0x4d fp=0xc00014b5b8 sp=0xc00014b590 pc=0x9ee3cd
github.com/flier/gorocksdb.OpenDbColumnFamilies.func3(0x112da76, 0xb, 0x8, 0xc00014b738, 0xc00014b720, 0xc00014b750, 0xc000042000)
	/home/blockbook/go/pkg/mod/github.com/flier/gorocksdb@v0.0.0-20210322035443-567cc51a1652/db.go:123 +0x1b1 fp=0xc00014b638 sp=0xc00014b5b8 pc=0x9f8571
github.com/flier/gorocksdb.OpenDbColumnFamilies(0xc0000d6fc0, {0x7fff99c0bd4d, 0xc0000001a0}, {0xc000268000, 0x8, 0xc0000001a0}, {0xc000112840, 0x8, 0x0})
	/home/blockbook/go/pkg/mod/github.com/flier/gorocksdb@v0.0.0-20210322035443-567cc51a1652/db.go:123 +0x2f2 fp=0xc00014b790 sp=0xc00014b638 pc=0x9f7eb2
github.com/trezor/blockbook/db.openDB({0x7fff99c0bd4d, 0x1e}, 0x11569bb, 0x1b96c00)
	/home/blockbook/go/src/blockbook/db/rocksdb.go:138 +0x187 fp=0xc00014b848 sp=0xc00014b790 pc=0xa16827
github.com/trezor/blockbook/db.NewRocksDB({0x7fff99c0bd4d, 0x5}, 0x7fff99c0bcc1, 0x4000, {0x138d230, 0xc0001247e0}, 0xc000248360)
	/home/blockbook/go/src/blockbook/db/rocksdb.go:161 +0x458 fp=0xc00014b968 sp=0xc00014b848 pc=0xa16cf8
main.mainWithExitCode()
	/home/blockbook/go/src/blockbook/blockbook.go:178 +0x6f0 fp=0xc00014bf58 sp=0xc00014b968 pc=0xc32330
main.main()
	/home/blockbook/go/src/blockbook/blockbook.go:124 +0x3b fp=0xc00014bf80 sp=0xc00014bf58 pc=0xc31bfb
runtime.main()
	/tmp/go/src/runtime/proc.go:255 +0x227 fp=0xc00014bfe0 sp=0xc00014bf80 pc=0x561c47
runtime.goexit()
	/tmp/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00014bfe8 sp=0xc00014bfe0 pc=0x592801
goroutine 4 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0)
	/home/blockbook/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/home/blockbook/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x1c5
goroutine 12 [syscall]:
os/signal.signal_recv()
	/tmp/go/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
	/tmp/go/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	/tmp/go/src/os/signal/signal.go:151 +0x2c
goroutine 15 [chan receive]:
github.com/trezor/blockbook/bchain.NewMempoolBitcoinType.func1(0xc0001545a0)
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:47 +0x237
created by github.com/trezor/blockbook/bchain.NewMempoolBitcoinType
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:36 +0x138
goroutine 71 [chan receive]:
github.com/trezor/blockbook/bchain.NewMempoolBitcoinType.func1.1(0xc0001545a0)
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:41 +0x88
created by github.com/trezor/blockbook/bchain.NewMempoolBitcoinType.func1
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:40 +0x72
```

**Comment by martinboehm** [comment]
It crashes while opening the DB. Could it be corrupted?

**Comment by APshenkin** [comment]
How we can verify that it's corrupted? Sorry, didn't work a lot with rocksDB

Actually I think that it could be related with fact that BSV has a lot of transaction in the mempool

e.g. https://whatsonchain.com/ shows just 17k

but https://blockchair.com/bitcoin-sv shows 571k (actually few hours ago it shows something around 200k)

**Comment by martinboehm** [comment]
Now there are only a few transactions so if your hypothesis is correct, it should work now. If it crashes due to too many transactions in the mempool then it is probably an out of memory issue.

While we do not run BSV Blockbooks, our Ethereum Blockbooks have regularly hundreds of thousands of transactions in mempool (and BTC in the peek times too) and we did not observe any problems.

To check the integrity of the database, you can run Blockbook with the `-repair` parameter or use the `ldb` tool.

**Comment by martinboehm** [comment]
Is it working now?

**Comment by APshenkin** [comment]
The issue was not resolved. After repair it actually just dropped the state

We started resync on other node 5 days ago and now get same error on fresh resync
```
github.com/trezor/blockbook/bchain.NewMempoolBitcoinType.func1(0xc0000ccd80)
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:47 +0x237
created by github.com/trezor/blockbook/bchain.NewMempoolBitcoinType
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:36 +0x138
goroutine 42 [chan receive]:
github.com/trezor/blockbook/bchain.NewMempoolBitcoinType.func1.1(0x0)
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:41 +0x88
created by github.com/trezor/blockbook/bchain.NewMempoolBitcoinType.func1
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:40 +0x72
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fb56f4f2313 pc=0x7fb91702337d]
runtime stack:
runtime.throw({0x11495dd, 0x7fb8d400ab00})
	/tmp/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/tmp/go/src/runtime/signal_unix.go:719 +0x396
goroutine 1 [syscall]:
runtime.cgocall(0xc3c448, 0xc0000c15b8)
	/tmp/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0000c1590 sp=0xc0000c1558 pc=0x52d1dc
github.com/flier/gorocksdb._Cfunc_rocksdb_open_column_families(0x7fb8d4007030, 0x7fb8d400a4f0, 0x8, 0xc000016580, 0xc000012340, 0xc000012380, 0xc0001344a8)
	_cgo_gotypes.go:2261 +0x4d fp=0xc0000c15b8 sp=0xc0000c1590 pc=0x9ee3cd
github.com/flier/gorocksdb.OpenDbColumnFamilies.func3(0x112de16, 0xb, 0x8, 0xc0000c1738, 0xc0000c1720, 0xc0000c1750, 0xc000044800)
	/home/blockbook/go/pkg/mod/github.com/flier/gorocksdb@v0.0.0-20210322035443-567cc51a1652/db.go:123 +0x1b1 fp=0xc0000c1638 sp=0xc0000c15b8 pc=0x9f8571
github.com/flier/gorocksdb.OpenDbColumnFamilies(0xc000016500, {0x7fff42fa9d4d, 0xc0000001a0}, {0xc00021c000, 0x8, 0xc0000001a0}, {0xc000137980, 0x8, 0xc000044800})
	/home/blockbook/go/pkg/mod/github.com/flier/gorocksdb@v0.0.0-20210322035443-567cc51a1652/db.go:123 +0x2f2 fp=0xc0000c1790 sp=0xc0000c1638 pc=0x9f7eb2
github.com/trezor/blockbook/db.openDB({0x7fff42fa9d4d, 0x1e}, 0x1156ce4, 0x1b97c00)
	/home/blockbook/go/src/blockbook/db/rocksdb.go:138 +0x187 fp=0xc0000c1848 sp=0xc0000c1790 pc=0xa16827
github.com/trezor/blockbook/db.NewRocksDB({0x7fff42fa9d4d, 0x5}, 0x7fff42fa9cc1, 0x4000, {0x138d6f0, 0xc00021f210}, 0xc0000b4120)
	/home/blockbook/go/src/blockbook/db/rocksdb.go:161 +0x458 fp=0xc0000c1968 sp=0xc0000c1848 pc=0xa16cf8
main.mainWithExitCode()
	/home/blockbook/go/src/blockbook/blockbook.go:178 +0x6f0 fp=0xc0000c1f58 sp=0xc0000c1968 pc=0xc325f0
main.main()
	/home/blockbook/go/src/blockbook/blockbook.go:124 +0x3b fp=0xc0000c1f80 sp=0xc0000c1f58 pc=0xc31ebb
runtime.main()
	/tmp/go/src/runtime/proc.go:255 +0x227 fp=0xc0000c1fe0 sp=0xc0000c1f80 pc=0x561c47
runtime.goexit()
	/tmp/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000c1fe8 sp=0xc0000c1fe0 pc=0x592801
goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0)
	/home/blockbook/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/home/blockbook/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x1c5
goroutine 50 [syscall]:
os/signal.signal_recv()
	/tmp/go/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
	/tmp/go/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	/tmp/go/src/os/signal/signal.go:151 +0x2c
goroutine 97 [chan receive]:
github.com/trezor/blockbook/bchain.NewMempoolBitcoinType.func1(0xc0001ae240)
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:47 +0x237
created by github.com/trezor/blockbook/bchain.NewMempoolBitcoinType
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:36 +0x138
goroutine 26 [chan receive]:
github.com/trezor/blockbook/bchain.NewMempoolBitcoinType.func1.1(0xc0001ae240)
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:41 +0x88
created by github.com/trezor/blockbook/bchain.NewMempoolBitcoinType.func1
	/home/blockbook/go/src/blockbook/bchain/mempool_bitcoin_type.go:40 +0x72
	```

**Comment by APshenkin** [comment]
Now it failed on block 756183

**Comment by martinboehm** [comment]
Could it be that the server goes out of memory? BSV has some huge blocks.

**Comment by APshenkin** [comment]
From what I can see there was no. Here is a screenshot of period, when we tried to resync state

![image](https://user-images.githubusercontent.com/14344430/192059830-6d796279-dfc5-4df6-9e94-cf912ffb53f4.png)

**Comment by luoxiandong** [comment]
same issue, my  server 32core 256ram.

**Comment by luoxiandong** [comment]
Is this problem solved?

**Comment by martinboehm** [comment]
Hi, it looks like a really strange problem. Unfortunately, I cannot try to reproduce it as I do not run any BSV instance.

I found out the discussion of a similar issue (although a bit old) here https://github.com/golang/go/issues/41099#issuecomment-841848694, you could try to build Blockbook with the `GODEBUG=asyncpreemptoff=1` evironment variable.

Or you could try to build Blockbook from the new release branch `v0.4.0`. It uses go 1.19 and rocksdb 7.5.3, maybe the new go (or rocksdb) version will fix the issue. Just a warning, while the branch is already fairly stable, it is not yet fully ready for release. Blockbook will still report itself as `v0.3.6` but will upgrade the db data to a higher version so you will not be able to use the Blockbook built  from `master` branch any more. If you have enough disc space, I would create a copy of Blockbook DB and run the `v0.4.0` against it first.

**Comment by APshenkin** [comment]
Upgrading to 0.4.0 with go 1.19 and rocksdb 7.5.3 solved the issue for us

Also we applied this small patch for BSV https://github.com/trezor/blockbook/pull/427 because syncing BSV goes faster with it

**Comment by wo4zhuzi** [comment]
> Upgrading to 0.4.0 with go 1.19 and rocksdb 7.5.3 solved the issue for us
> 
> Also we applied this small patch for BSV #427 because syncing BSV goes faster with it

@APshenkin
